@baseUrl = http://localhost:5234

###
GET {{baseUrl}}/route-table

### Adding new Patient
POST {{baseUrl}}/patients
Content-Type: application/json
Accept: application/json

{
  "FirstName" : "Ameer",
  "LastName" : "Ameer",
  "Age" : 20 , 
  "Symptoms" : "Nothing-Alhamdullah",
  "Medicine" : "idk",
  "Diagnostic" : "notin",
  "DoctorId" : 11
}

### Updating Existing Patient
PUT {{baseUrl}}/patients/10
Content-Type: application/json

{  "patientId": 0,
  "FirstName" : "Ameer",
  "LastName" : "Ameer",
  "Age" : 20 , 
  "Symptoms" : "Nothing-Alhamdullah",
  "Medicine" : "idk",
  "Diagnostic" : "notin",
  "DoctorId" : 11
}

### Adding new Doctor
POST {{baseUrl}}/doctors
Content-Type: application/json
Accept: application/json

{
  "FirstName": "Ahmad",
  "LastName": "Salameh",
  "Specialist": "Cardiology",
  "Age": 40,
  "YearOfExperience": 12
}

### Updating Existing Doctor
PUT {{baseUrl}}/doctors/10
Content-Type: application/json
Accept: application/json

{
  "DoctorId": 0,
  "FirstName": "Ahmad",
  "LastName": "Salameh",
  "Specialist": "Cardiology",
  "Age": 41,
  "YearOfExperience": 13
}

### Adding new Appointment
POST {{baseUrl}}/appointments
Content-Type: application/json
Accept: application/json

{
  "PatientId": 5,
  "DoctorId": 10,
  "Date": "2025-12-20"
}

### Updating Existing Appointment
PUT {{baseUrl}}/appointments/10
Content-Type: application/json
Accept: application/json

{
  "AppointmentId": 0,
  "PatientId": 5,
  "DoctorId": 10,
  "Date": "2025-12-22"
}