// <auto-generated />
using System;
using ClinicAPI.Presistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicAPI.Presistence.Migrations
{
    [DbContext(typeof(ClinicDbContext))]
    [Migration("20260108123312_UpdatedStuff")]
    partial class UpdatedStuff
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("ClinicAPI.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diagnostic")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Medicine")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("AppointmentId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments", (string)null);

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 14, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Date = new DateTimeOffset(new DateTime(2025, 12, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            DoctorId = 7,
                            IsDeleted = false,
                            IsDone = false,
                            PatientId = 1,
                            Symptoms = "Headache"
                        },
                        new
                        {
                            AppointmentId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 14, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Date = new DateTimeOffset(new DateTime(2025, 12, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Diagnostic = "Dermatitis",
                            DoctorId = 2,
                            IsDeleted = false,
                            IsDone = true,
                            Medicine = "Cream",
                            PatientId = 2,
                            Symptoms = "Skin rash"
                        },
                        new
                        {
                            AppointmentId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 15, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Date = new DateTimeOffset(new DateTime(2025, 12, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            DoctorId = 3,
                            IsDeleted = false,
                            IsDone = false,
                            PatientId = 3,
                            Symptoms = "Knee pain"
                        },
                        new
                        {
                            AppointmentId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 15, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Date = new DateTimeOffset(new DateTime(2025, 12, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            DoctorId = 5,
                            IsDeleted = false,
                            IsDone = false,
                            PatientId = 4,
                            Symptoms = "Sore throat"
                        },
                        new
                        {
                            AppointmentId = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 16, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Date = new DateTimeOffset(new DateTime(2025, 12, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            DoctorId = 1,
                            IsDeleted = false,
                            IsDone = false,
                            PatientId = 5,
                            Symptoms = "Chest pain"
                        },
                        new
                        {
                            AppointmentId = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 16, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Date = new DateTimeOffset(new DateTime(2025, 12, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Diagnostic = "Dry eye",
                            DoctorId = 8,
                            IsDeleted = false,
                            IsDone = true,
                            Medicine = "Eye drops",
                            PatientId = 6,
                            Symptoms = "Blurred vision"
                        },
                        new
                        {
                            AppointmentId = 7,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 17, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Date = new DateTimeOffset(new DateTime(2025, 12, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            DoctorId = 4,
                            IsDeleted = false,
                            IsDone = false,
                            PatientId = 7,
                            Symptoms = "Fever"
                        },
                        new
                        {
                            AppointmentId = 8,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 17, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Date = new DateTimeOffset(new DateTime(2025, 12, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            DoctorId = 3,
                            IsDeleted = false,
                            IsDone = false,
                            PatientId = 8,
                            Symptoms = "Back pain"
                        },
                        new
                        {
                            AppointmentId = 9,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Date = new DateTimeOffset(new DateTime(2025, 12, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            DoctorId = 7,
                            IsDeleted = false,
                            IsDone = false,
                            PatientId = 9,
                            Symptoms = "Dizziness"
                        },
                        new
                        {
                            AppointmentId = 10,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Date = new DateTimeOffset(new DateTime(2025, 12, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            DoctorId = 6,
                            IsDeleted = false,
                            IsDone = false,
                            PatientId = 10,
                            Symptoms = "Migraine"
                        });
                });

            modelBuilder.Entity("ClinicAPI.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Roles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("YearOfExperience")
                        .HasColumnType("INTEGER");

                    b.HasKey("DoctorId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Doctors", (string)null);

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            Age = 40,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "ahmad.khalil@clinic.test",
                            FirstName = "Ahmad",
                            IsDeleted = false,
                            LastName = "Khalil",
                            PasswordHash = "HASH",
                            Permissions = "[\"patient:read\",\"patient:create\",\"patient:update\",\"patient:delete\",\"patient:read-appointments\",\"patient:manage-doctor\",\"patient:manage-appointments\",\"doctor:read\",\"doctor:create\",\"doctor:update\",\"doctor:delete\",\"doctor:read-patients\",\"doctor:read-appointments\",\"doctor:delete-patient\",\"doctor:add-patient\",\"doctor:update-specialty\",\"appointment:read\",\"appointment:create\",\"appointment:update\",\"appointment:delete\",\"appointment:update-status\",\"appointment:manage-patient\",\"appointment:manage-doctor\",\"appointment:update-date\"]",
                            Phone = "+970599000001",
                            Roles = "[\"Doctor\"]",
                            Specialty = "Cardiology",
                            YearOfExperience = 15
                        },
                        new
                        {
                            DoctorId = 2,
                            Age = 34,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "rana.haddad@clinic.test",
                            FirstName = "Rana",
                            IsDeleted = false,
                            LastName = "Haddad",
                            PasswordHash = "HASH",
                            Permissions = "[]",
                            Phone = "+970599000002",
                            Roles = "[\"Doctor\"]",
                            Specialty = "Dermatology",
                            YearOfExperience = 10
                        },
                        new
                        {
                            DoctorId = 3,
                            Age = 38,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "omar.safi@clinic.test",
                            FirstName = "Omar",
                            IsDeleted = false,
                            LastName = "Safi",
                            PasswordHash = "HASH",
                            Permissions = "[]",
                            Phone = "+970599000003",
                            Roles = "[\"Doctor\"]",
                            Specialty = "Orthopedics",
                            YearOfExperience = 12
                        },
                        new
                        {
                            DoctorId = 4,
                            Age = 33,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "lina.barghouti@clinic.test",
                            FirstName = "Lina",
                            IsDeleted = false,
                            LastName = "Barghouti",
                            PasswordHash = "HASH",
                            Permissions = "[]",
                            Phone = "+970599000004",
                            Roles = "[\"Doctor\"]",
                            Specialty = "Pediatrics",
                            YearOfExperience = 8
                        },
                        new
                        {
                            DoctorId = 5,
                            Age = 45,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "yousef.nassar@clinic.test",
                            FirstName = "Yousef",
                            IsDeleted = false,
                            LastName = "Nassar",
                            PasswordHash = "HASH",
                            Permissions = "[]",
                            Phone = "+970599000005",
                            Roles = "[\"Doctor\"]",
                            Specialty = "ENT",
                            YearOfExperience = 20
                        },
                        new
                        {
                            DoctorId = 6,
                            Age = 41,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "hala.masri@clinic.test",
                            FirstName = "Hala",
                            IsDeleted = false,
                            LastName = "Masri",
                            PasswordHash = "HASH",
                            Permissions = "[]",
                            Phone = "+970599000006",
                            Roles = "[\"Doctor\"]",
                            Specialty = "Neurology",
                            YearOfExperience = 16
                        },
                        new
                        {
                            DoctorId = 7,
                            Age = 36,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "tariq.qasem@clinic.test",
                            FirstName = "Tariq",
                            IsDeleted = false,
                            LastName = "Qasem",
                            PasswordHash = "HASH",
                            Permissions = "[]",
                            Phone = "+970599000007",
                            Roles = "[\"Doctor\"]",
                            Specialty = "Cardiology",
                            YearOfExperience = 11
                        },
                        new
                        {
                            DoctorId = 8,
                            Age = 29,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "maya.ayyad@clinic.test",
                            FirstName = "Maya",
                            IsDeleted = false,
                            LastName = "Ayyad",
                            PasswordHash = "HASH",
                            Permissions = "[]",
                            Phone = "+970599000008",
                            Roles = "[\"Doctor\"]",
                            Specialty = "GeneralPractice",
                            YearOfExperience = 5
                        },
                        new
                        {
                            DoctorId = 9,
                            Age = 39,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "nabil.salameh@clinic.test",
                            FirstName = "Nabil",
                            IsDeleted = false,
                            LastName = "Salameh",
                            PasswordHash = "HASH",
                            Permissions = "[]",
                            Phone = "+970599000009",
                            Roles = "[\"Doctor\"]",
                            Specialty = "Neurology",
                            YearOfExperience = 13
                        },
                        new
                        {
                            DoctorId = 10,
                            Age = 32,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "sara.zaid@clinic.test",
                            FirstName = "Sara",
                            IsDeleted = false,
                            LastName = "Zaid",
                            PasswordHash = "HASH",
                            Permissions = "[]",
                            Phone = "+970599000010",
                            Roles = "[\"Doctor\"]",
                            Specialty = "Orthopedics",
                            YearOfExperience = 7
                        });
                });

            modelBuilder.Entity("ClinicAPI.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Roles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PatientId");

                    b.HasIndex("DoctorId");

                    b.ToTable("Patients", (string)null);

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            Age = 20,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = 7,
                            Email = "ameer.tamimi@clinic.test",
                            FirstName = "Ameer",
                            IsDeleted = false,
                            LastName = "Tamimi",
                            PasswordHash = "HASH",
                            Permissions = "[\"patient:read\",\"patient:create\",\"patient:update\",\"patient:delete\",\"patient:read-appointments\",\"patient:manage-doctor\",\"patient:manage-appointments\",\"doctor:read\",\"doctor:create\",\"doctor:update\",\"doctor:delete\",\"doctor:read-patients\",\"doctor:read-appointments\",\"doctor:delete-patient\",\"doctor:add-patient\",\"doctor:update-specialty\",\"appointment:read\",\"appointment:create\",\"appointment:update\",\"appointment:delete\",\"appointment:update-status\",\"appointment:manage-patient\",\"appointment:manage-doctor\",\"appointment:update-date\"]",
                            Phone = "+970599001001",
                            Roles = "[\"Patient\"]"
                        },
                        new
                        {
                            PatientId = 2,
                            Age = 21,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = 2,
                            Email = "hareth.shoman@clinic.test",
                            FirstName = "Hareth",
                            IsDeleted = false,
                            LastName = "Shoman",
                            PasswordHash = "HASH",
                            Permissions = "[]",
                            Phone = "+970599001002",
                            Roles = "[\"Patient\"]"
                        },
                        new
                        {
                            PatientId = 3,
                            Age = 22,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = 3,
                            Email = "elyas.najeh@clinic.test",
                            FirstName = "Elyas",
                            IsDeleted = false,
                            LastName = "Najeh",
                            PasswordHash = "HASH",
                            Permissions = "[]",
                            Phone = "+970599001003",
                            Roles = "[\"Patient\"]"
                        },
                        new
                        {
                            PatientId = 4,
                            Age = 30,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = 5,
                            Email = "mariam.yasin@clinic.test",
                            FirstName = "Mariam",
                            IsDeleted = false,
                            LastName = "Yasin",
                            PasswordHash = "HASH",
                            Permissions = "[]",
                            Phone = "+970599001004",
                            Roles = "[\"Patient\"]"
                        },
                        new
                        {
                            PatientId = 5,
                            Age = 28,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = 1,
                            Email = "kareem.abulail@clinic.test",
                            FirstName = "Kareem",
                            IsDeleted = false,
                            LastName = "AbuLail",
                            PasswordHash = "HASH",
                            Permissions = "[]",
                            Phone = "+970599001005",
                            Roles = "[\"Patient\"]"
                        },
                        new
                        {
                            PatientId = 6,
                            Age = 19,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = 8,
                            Email = "noor.said@clinic.test",
                            FirstName = "Noor",
                            IsDeleted = false,
                            LastName = "Said",
                            PasswordHash = "HASH",
                            Permissions = "[]",
                            Phone = "+970599001006",
                            Roles = "[\"Patient\"]"
                        },
                        new
                        {
                            PatientId = 7,
                            Age = 23,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = 4,
                            Email = "zaid.qamhieh@clinic.test",
                            FirstName = "Zaid",
                            IsDeleted = false,
                            LastName = "Qamhieh",
                            PasswordHash = "HASH",
                            Permissions = "[]",
                            Phone = "+970599001007",
                            Roles = "[\"Patient\"]"
                        },
                        new
                        {
                            PatientId = 8,
                            Age = 24,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = 3,
                            Email = "habeeb.ahmad@clinic.test",
                            FirstName = "Habeeb",
                            IsDeleted = false,
                            LastName = "Ahmad",
                            PasswordHash = "HASH",
                            Permissions = "[]",
                            Phone = "+970599001008",
                            Roles = "[\"Patient\"]"
                        },
                        new
                        {
                            PatientId = 9,
                            Age = 26,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = 7,
                            Email = "waleed.noubani@clinic.test",
                            FirstName = "Waleed",
                            IsDeleted = false,
                            LastName = "Noubani",
                            PasswordHash = "HASH",
                            Permissions = "[]",
                            Phone = "+970599001009",
                            Roles = "[\"Patient\"]"
                        },
                        new
                        {
                            PatientId = 10,
                            Age = 29,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = 6,
                            Email = "ruba.katout@clinic.test",
                            FirstName = "Ruba",
                            IsDeleted = false,
                            LastName = "Katout",
                            PasswordHash = "HASH",
                            Permissions = "[]",
                            Phone = "+970599001010",
                            Roles = "[\"Patient\"]"
                        });
                });

            modelBuilder.Entity("ClinicAPI.Models.Appointment", b =>
                {
                    b.HasOne("ClinicAPI.Models.Doctor", "Doctor")
                        .WithMany("DoctorAppointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicAPI.Models.Patient", "Patient")
                        .WithMany("PatientAppointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicAPI.Models.Patient", b =>
                {
                    b.HasOne("ClinicAPI.Models.Doctor", "Doctor")
                        .WithMany("DoctorPatients")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("ClinicAPI.Models.Doctor", b =>
                {
                    b.Navigation("DoctorAppointments");

                    b.Navigation("DoctorPatients");
                });

            modelBuilder.Entity("ClinicAPI.Models.Patient", b =>
                {
                    b.Navigation("PatientAppointments");
                });
#pragma warning restore 612, 618
        }
    }
}
