// <auto-generated />
using System;
using ClinicAPI.Presistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicAPI.Presistence.Migrations
{
    [DbContext(typeof(ClinicDbContext))]
    partial class ClinicDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("ClinicAPI.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diagnostic")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Medicine")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("AppointmentId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments", (string)null);

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 14, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Date = new DateTimeOffset(new DateTime(2025, 12, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            DoctorId = 7,
                            IsDeleted = false,
                            IsDone = false,
                            PatientId = 1,
                            Symptoms = "Headache"
                        },
                        new
                        {
                            AppointmentId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 14, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Date = new DateTimeOffset(new DateTime(2025, 12, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Diagnostic = "Dermatitis",
                            DoctorId = 2,
                            IsDeleted = false,
                            IsDone = true,
                            Medicine = "Cream",
                            PatientId = 2,
                            Symptoms = "Skin rash"
                        },
                        new
                        {
                            AppointmentId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 15, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Date = new DateTimeOffset(new DateTime(2025, 12, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            DoctorId = 3,
                            IsDeleted = false,
                            IsDone = false,
                            PatientId = 3,
                            Symptoms = "Knee pain"
                        },
                        new
                        {
                            AppointmentId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 15, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Date = new DateTimeOffset(new DateTime(2025, 12, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            DoctorId = 5,
                            IsDeleted = false,
                            IsDone = false,
                            PatientId = 4,
                            Symptoms = "Sore throat"
                        },
                        new
                        {
                            AppointmentId = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 16, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Date = new DateTimeOffset(new DateTime(2025, 12, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            DoctorId = 1,
                            IsDeleted = false,
                            IsDone = false,
                            PatientId = 5,
                            Symptoms = "Chest pain"
                        },
                        new
                        {
                            AppointmentId = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 16, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Date = new DateTimeOffset(new DateTime(2025, 12, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Diagnostic = "Dry eye",
                            DoctorId = 8,
                            IsDeleted = false,
                            IsDone = true,
                            Medicine = "Eye drops",
                            PatientId = 6,
                            Symptoms = "Blurred vision"
                        },
                        new
                        {
                            AppointmentId = 7,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 17, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Date = new DateTimeOffset(new DateTime(2025, 12, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            DoctorId = 4,
                            IsDeleted = false,
                            IsDone = false,
                            PatientId = 7,
                            Symptoms = "Fever"
                        },
                        new
                        {
                            AppointmentId = 8,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 17, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Date = new DateTimeOffset(new DateTime(2025, 12, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            DoctorId = 3,
                            IsDeleted = false,
                            IsDone = false,
                            PatientId = 8,
                            Symptoms = "Back pain"
                        },
                        new
                        {
                            AppointmentId = 9,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Date = new DateTimeOffset(new DateTime(2025, 12, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            DoctorId = 7,
                            IsDeleted = false,
                            IsDone = false,
                            PatientId = 9,
                            Symptoms = "Dizziness"
                        },
                        new
                        {
                            AppointmentId = 10,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Date = new DateTimeOffset(new DateTime(2025, 12, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            DoctorId = 6,
                            IsDeleted = false,
                            IsDone = false,
                            PatientId = 10,
                            Symptoms = "Migraine"
                        });
                });

            modelBuilder.Entity("ClinicAPI.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("YearOfExperience")
                        .HasColumnType("INTEGER");

                    b.HasKey("DoctorId");

                    b.ToTable("Doctors", (string)null);

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            Age = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Ahmad",
                            IsDeleted = false,
                            LastName = "Khalil",
                            Phone = "+970599000001",
                            Specialty = "Cardiology",
                            YearOfExperience = 0
                        },
                        new
                        {
                            DoctorId = 2,
                            Age = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Rana",
                            IsDeleted = false,
                            LastName = "Haddad",
                            Phone = "+970599000002",
                            Specialty = "Dermatology",
                            YearOfExperience = 0
                        },
                        new
                        {
                            DoctorId = 3,
                            Age = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Omar",
                            IsDeleted = false,
                            LastName = "Safi",
                            Phone = "+970599000003",
                            Specialty = "Orthopedics",
                            YearOfExperience = 0
                        },
                        new
                        {
                            DoctorId = 4,
                            Age = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Lina",
                            IsDeleted = false,
                            LastName = "Barghouti",
                            Phone = "+970599000004",
                            Specialty = "Pediatrics",
                            YearOfExperience = 0
                        },
                        new
                        {
                            DoctorId = 5,
                            Age = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Yousef",
                            IsDeleted = false,
                            LastName = "Nassar",
                            Phone = "+970599000005",
                            Specialty = "ENT",
                            YearOfExperience = 0
                        },
                        new
                        {
                            DoctorId = 6,
                            Age = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Hala",
                            IsDeleted = false,
                            LastName = "Masri",
                            Phone = "+970599000006",
                            Specialty = "Neurology",
                            YearOfExperience = 0
                        },
                        new
                        {
                            DoctorId = 7,
                            Age = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Tariq",
                            IsDeleted = false,
                            LastName = "Qasem",
                            Phone = "+970599000007",
                            Specialty = "Cardiology",
                            YearOfExperience = 0
                        },
                        new
                        {
                            DoctorId = 8,
                            Age = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Maya",
                            IsDeleted = false,
                            LastName = "Ayyad",
                            Phone = "+970599000008",
                            Specialty = "GeneralPractice",
                            YearOfExperience = 0
                        },
                        new
                        {
                            DoctorId = 9,
                            Age = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Nabil",
                            IsDeleted = false,
                            LastName = "Salameh",
                            Phone = "+970599000009",
                            Specialty = "Neurology",
                            YearOfExperience = 0
                        },
                        new
                        {
                            DoctorId = 10,
                            Age = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Sara",
                            IsDeleted = false,
                            LastName = "Zaid",
                            Phone = "+970599000010",
                            Specialty = "Orthopedics",
                            YearOfExperience = 0
                        });
                });

            modelBuilder.Entity("ClinicAPI.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("PatientId");

                    b.HasIndex("DoctorId");

                    b.ToTable("Patients", (string)null);

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            Age = 20,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = 7,
                            FirstName = "Ameer",
                            IsDeleted = false,
                            LastName = "Tamimi"
                        },
                        new
                        {
                            PatientId = 2,
                            Age = 21,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = 2,
                            FirstName = "Hareth",
                            IsDeleted = false,
                            LastName = "Shoman"
                        },
                        new
                        {
                            PatientId = 3,
                            Age = 22,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = 3,
                            FirstName = "Elyas",
                            IsDeleted = false,
                            LastName = "Najeh"
                        },
                        new
                        {
                            PatientId = 4,
                            Age = 30,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = 5,
                            FirstName = "Mariam",
                            IsDeleted = false,
                            LastName = "Yasin"
                        },
                        new
                        {
                            PatientId = 5,
                            Age = 28,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = 1,
                            FirstName = "Kareem",
                            IsDeleted = false,
                            LastName = "AbuLail"
                        },
                        new
                        {
                            PatientId = 6,
                            Age = 19,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = 8,
                            FirstName = "Noor",
                            IsDeleted = false,
                            LastName = "Said"
                        },
                        new
                        {
                            PatientId = 7,
                            Age = 23,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = 4,
                            FirstName = "Zaid",
                            IsDeleted = false,
                            LastName = "Qamhieh"
                        },
                        new
                        {
                            PatientId = 8,
                            Age = 24,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = 3,
                            FirstName = "Habeeb",
                            IsDeleted = false,
                            LastName = "Ahmad"
                        },
                        new
                        {
                            PatientId = 9,
                            Age = 26,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = 7,
                            FirstName = "Waleed",
                            IsDeleted = false,
                            LastName = "Noubani"
                        },
                        new
                        {
                            PatientId = 10,
                            Age = 29,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = 6,
                            FirstName = "Ruba",
                            IsDeleted = false,
                            LastName = "Katout"
                        });
                });

            modelBuilder.Entity("ClinicAPI.Models.Appointment", b =>
                {
                    b.HasOne("ClinicAPI.Models.Doctor", "Doctor")
                        .WithMany("DoctorAppointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicAPI.Models.Patient", "Patient")
                        .WithMany("PatientAppointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicAPI.Models.Patient", b =>
                {
                    b.HasOne("ClinicAPI.Models.Doctor", "Doctor")
                        .WithMany("DoctorPatients")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("ClinicAPI.Models.Doctor", b =>
                {
                    b.Navigation("DoctorAppointments");

                    b.Navigation("DoctorPatients");
                });

            modelBuilder.Entity("ClinicAPI.Models.Patient", b =>
                {
                    b.Navigation("PatientAppointments");
                });
#pragma warning restore 612, 618
        }
    }
}
